### PR TITLE
fix: fcitx5-migrator tweak

### PR DESCRIPTION
**Pull request by kegechen**
fix
- https://github.com/linuxdeepin/developer-center/issues/7442
- https://github.com/linuxdeepin/developer-center/issues/7443

### CODE REVIEW

**Comment by kegechen** [comment]
b4
image

now
image

**Comment by kegechen** [comment]
上游 fcitx5 不太喜欢合并这种小改动， 就不提了把。。

**Comment by kegechen** [comment]
@BLumia

**Review by BLumia — APPROVED** [review]

**Review by xzl01 — APPROVED** [review]

**Pull request merged**
